force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>プロジェクト</label>
    <nameField>
        <label>プロジェクト名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ProjectNumber__c</fullName>
    <label>プロジェクト番号</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>開始日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>ステータス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>準備中</fullName>
            </value>
            <value>
                <fullName>進行中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
            <value>
                <fullName>中止</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>タスク</label>
    <nameField>
        <label>タスク名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <label>担当</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>またえ</fullName>
            </value>
            <value>
                <fullName>たかはし</fullName>
            </value>
            <value>
                <fullName>わたなべ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>終了日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>プロジェクト</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>タスク</relationshipLabel>
    <relationshipName>TaskProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>ステータス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>未着手</fullName>
            </value>
            <value>
                <fullName>進行中</fullName>
            </value>
            <value>
                <fullName>完了</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Project.cls
public with sharing class Project {
  /**
   * プロジェクトを登録する
   */
  @AuraEnabled
  public static void registProject(String projectJson, String tasksJson) {
    try {
      Map<String, Object> mapProject = (Map<String, Object>) JSON.deserializeUntyped(
        projectJson
      );

      Project__c project = new Project__c();
      project.Id = (Id) mapProject.get('Id');
      project.Name = (String) mapProject.get('Name');
      project.ProjectNumber__c = (String) mapProject.get('ProjectNumber__c');
      if (mapProject.get('StartDate__c') != null) {
        project.StartDate__c = Date.valueOf(
          (String) mapProject.get('StartDate__c')
        );
      } else {
        project.StartDate__c = null;
      }
      if (mapProject.get('EndDate__c') != null) {
        project.EndDate__c = Date.valueOf(
          (String) mapProject.get('EndDate__c')
        );
      } else {
        project.EndDate__c = null;
      }
      project.Status__c = (String) mapProject.get('Status__c');

      List<Task__c> lstTask = new List<Task__c>();
      List<Object> lstTaskItem = (List<Object>) JSON.deserializeUntyped(
        tasksJson
      );
      for (Object taskItem : lstTaskItem) {
        Map<String, Object> mapTaskItem = (Map<String, Object>) taskItem;
        Task__c task = new Task__c();
        if (mapTaskItem.get('Id') != null) {
          task.Id = (Id) mapTaskItem.get('Id');
        } else {
          task.Project__c = project.Id;
        }
        task.Name = (String) mapTaskItem.get('Name');
        if (mapTaskItem.get('StartDate__c') != null) {
          task.StartDate__c = Date.valueOf(
            (String) mapTaskItem.get('StartDate__c')
          );
        }
        if (mapTaskItem.get('EndDate__c') != null) {
          task.EndDate__c = Date.valueOf(
            (String) mapTaskItem.get('EndDate__c')
          );
        }
        task.Status__c = (String) mapTaskItem.get('Status__c');
        task.Developer__c = (String) mapTaskItem.get('Developer__c');
        lstTask.add(task);
      }

      upsert project;
      upsert lstTask;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * プロジェクトのタスクを取得する
   */
  @AuraEnabled
  public static List<Task__c> getTasks(String projectId) {
    try {
      List<Task__c> lstTask = [
        SELECT Id, Name, Status__c, StartDate__c, EndDate__c, Developer__c
        FROM Task__c
        WHERE Project__c = :projectId
      ];

      return lstTask;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}